name: AoC 2021
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test AoC 2021
    runs-on: ubuntu-latest
    steps:
      - name: Install SWI-Prolog
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: stable
          swi-prolog-version: latest
      - name: Checkout AoC
        uses: actions/checkout@v1
      - name: Run tests for all days
        run: cd 2021 && ./testAll.sh
